/** Coach-facing copy — session/athlete-centric; avoid lane jargon in user-visible strings. */
export const SESSION_OPS_COPY = {
  pageTitle: 'Skating ops',
  pageSubtitle: 'Today’s sessions — pick one to coach on the floor.',
  emptyDayBoardBody:
    'No scheduled sessions on this day. Sessions from recurring schedules appear here automatically.',
  emptyRosterTitle: 'No athletes in this session yet',
  emptyRosterBody: 'Add athletes so you can observe and capture signals on the ice.',
  emptyRosterCta: 'Add athletes',
  captureDrawerTitle: 'Athlete details',
  markPresentSoon: 'Attendance from class roster — coming soon (no write yet).',
  focusPlaceholder: 'Today’s note for this athlete (one short line)',
  focusSave: 'Save note',
  focusSaved: 'Saved for this session.',
  openInlineCapture: 'Laps and quick notices stay in the main panel →',
  todayFocusInline: 'Today’s note',
  editFocusInPanel: 'Edit in side panel',
  sidePanel: 'Details',

  startModalTitle: 'Start live session',
  startModeScheduled: 'Scheduled batch',
  startModeQuick: 'Quick session',
  startPrimaryPlace: 'Place',
  startPrimaryCta: 'Start session',
  startAdvancedToggle: 'More options',
  startCoachLabel: 'Coach (optional)',
  startFocusLabel: 'Session focus (optional)',
  startTypeLabel: 'Session type (optional)',
  startSegmentationLabel: 'Timing lanes (advanced)',
  startSegmentationHint:
    'Only use when you run multiple timing lanes. Hidden until you add a lane.',
  startBatchLabel: 'Batch',
  startAthletesOptional: 'Athletes (optional before start)',
  startAthletesHint: 'You can start empty and add athletes on the ice.',
  cancel: 'Cancel',
  switchSession: 'Switch session',
  minimizeList: 'Minimize list',
  refresh: 'Refresh',
  dayLabel: 'Day',
  newSessionCta: 'Start live session',
  attendanceLink: 'Attendance',

  liveSessionTitle: 'Live session',
  recordingFor: 'Observing',
  selectAthletePrompt: 'Tap an athlete on the left to start recording observations.',
  addAthletesToRecord: 'Add athletes to begin recording.',
  lapEntryTitle: 'Save entry',
  timingSectionTitle: 'Timing & advanced metrics',
  timingSectionHint: 'Optional — use when you need lap times, effort tags, or lane context.',
  recordLapCta: 'Save entry',
  clearDraft: 'Clear draft',
  quickObservationsTitle: 'Quick observations',
  quickObservationsSubtitle: 'What did you notice? Tap a score — it saves automatically.',
  quickNoticeTitle: 'Signals',
  recentLapsTitle: 'Recent laps',
  athletesInSession: 'Who you’re observing',
  rosterFilterPlaceholder: 'Filter athletes…',
  timingLaneColumn: 'Lane',
  addDefaultLaneLegacy: 'Ensure default timing lane',
  addTimingLane: 'Add timing lane',
  guidancePickAthlete: 'Tap an athlete to start recording observations.',
  guidanceNoObsYet: 'Tap a score when something stands out — it syncs on its own.',
  observationSavedThisSession: 'Signal saved this session',

  /** Internal / dev-only labels */
  opsStateUpcoming: 'Upcoming',
}
