/** Coach-facing copy — session/student-centric; avoid lane jargon in user-visible strings. */
export const SESSION_OPS_COPY = {
  pageTitle: 'Skating ops',
  pageSubtitle: 'Today’s sessions — pick one to coach on the floor.',
  emptyDayBoardBody:
    'No scheduled sessions on this day. Sessions from recurring schedules appear here automatically.',
  emptyRosterTitle: 'No students yet',
  emptyRosterBody: 'Add students to coach on the ice.',
  emptyRosterCta: 'Add students',
  captureDrawerTitle: 'Student',
  markPresentSoon: 'Roster check-in — coming soon.',
  focusPlaceholder: 'Today note (short)',
  focusSave: 'Save',
  focusSaved: 'Saved.',
  openInlineCapture: 'Laps stay in main panel.',
  todayFocusInline: 'Today',
  editFocusInPanel: 'Edit note',
  sidePanel: 'Details',

  startModalTitle: 'Start live session',
  startModeScheduled: 'Scheduled batch',
  startModeQuick: 'Quick session',
  startPrimaryPlace: 'Place',
  startPrimaryCta: 'Start session',
  startAdvancedToggle: 'More options',
  startCoachLabel: 'Coach (optional)',
  startFocusLabel: 'Session focus (optional)',
  startTypeLabel: 'Session type (optional)',
  startSegmentationLabel: 'Timing lanes (advanced)',
  startSegmentationHint:
    'Only use when you run multiple timing lanes. Hidden until you add a lane.',
  startBatchLabel: 'Batch',
  startAthletesOptional: 'Students (optional before start)',
  startAthletesHint: 'You can start empty and add students on the ice.',
  cancel: 'Cancel',
  switchSession: 'Switch session',
  minimizeList: 'Minimize list',
  refresh: 'Refresh',
  dayLabel: 'Day',
  newSessionCta: 'Start live session',
  attendanceLink: 'Session participation',

  liveSessionTitle: 'Live',
  recordingFor: 'Student',
  selectAthletePrompt: 'Pick student',
  addAthletesToRecord: 'Add students',
  lapEntryTitle: 'Save',
  timingSectionTitle: 'Time',
  timingSectionHint: 'Lap times and effort tag.',
  recordLapCta: 'Save',
  clearDraft: 'Clear',
  quickObservationsTitle: 'Coach now',
  quickObservationsSubtitle: 'Tap score — saves on its own.',
  quickNoticeTitle: 'Tags',
  recentLapsTitle: 'Recent laps',
  athletesInSession: 'Students',
  rosterFilterPlaceholder: 'Filter…',
  timingLaneColumn: 'Lane',
  addDefaultLaneLegacy: 'Default lane',
  addTimingLane: 'Add lane',
  guidancePickAthlete: 'Pick student',
  guidanceNoObsYet: 'Tap score',
  observationSavedThisSession: 'Saved',

  /** Internal / dev-only labels */
  opsStateUpcoming: 'Upcoming',
}
