/** Coach-facing copy — session/athlete-centric; avoid lane jargon in user-visible strings. */
export const SESSION_OPS_COPY = {
  pageTitle: 'Skating ops',
  pageSubtitle: 'Live training sessions — the session is the workspace.',
  emptyRosterTitle: 'No athletes in this session yet',
  emptyRosterBody: 'Add athletes to begin recording laps and quick notices.',
  emptyRosterCta: 'Add athletes',
  captureDrawerTitle: 'Athlete details',
  markPresentSoon: 'Attendance from class roster — coming soon (no write yet).',
  focusPlaceholder: 'Today’s note for this athlete (one short line)',
  focusSave: 'Save note',
  focusSaved: 'Saved for this session.',
  openInlineCapture: 'Laps and quick notices stay in the main panel →',
  todayFocusInline: 'Today’s note',
  editFocusInPanel: 'Edit in side panel',
  sidePanel: 'Details',

  startModalTitle: 'Start live session',
  startModeScheduled: 'Scheduled batch',
  startModeQuick: 'Quick session',
  startPrimaryPlace: 'Place',
  startPrimaryCta: 'Start session',
  startAdvancedToggle: 'More options',
  startCoachLabel: 'Coach (optional)',
  startFocusLabel: 'Session focus (optional)',
  startTypeLabel: 'Session type (optional)',
  startSegmentationLabel: 'Timing lanes (advanced)',
  startSegmentationHint: 'Only use when you run multiple timing lanes. Hidden until you add a lane.',
  startBatchLabel: 'Batch',
  startAthletesOptional: 'Athletes (optional before start)',
  startAthletesHint: 'You can start empty and add athletes on the ice.',
  cancel: 'Cancel',
  switchSession: 'Switch session',
  minimizeList: 'Minimize list',
  refresh: 'Refresh',
  dayLabel: 'Day',
  newSessionCta: 'Start live session',
  attendanceLink: 'Attendance',

  liveSessionTitle: 'Live session',
  recordingFor: 'Recording for',
  selectAthletePrompt: 'Select an athlete on the left to record.',
  addAthletesToRecord: 'Add athletes to begin recording.',
  lapEntryTitle: 'Save entry',
  recordLapCta: 'Save entry',
  clearDraft: 'Clear draft',
  quickNoticeTitle: 'Quick notice',
  recentLapsTitle: 'Recent laps',
  athletesInSession: 'Athletes in session',
  rosterFilterPlaceholder: 'Filter athletes…',
  timingLaneColumn: 'Lane',
  addDefaultLaneLegacy: 'Ensure default timing lane',
  addTimingLane: 'Add timing lane',
  guidancePickAthlete: 'Select an athlete to record laps and quick notices.',
  guidanceNoObsYet: 'Tap a quick notice when something stands out.',

  /** Internal / dev-only labels */
  opsStateUpcoming: 'Upcoming',
}
